// Mock data — acts as the application's data layer.
// Replace with real API calls when backend is ready.

export const mockUser = {
  id: 1,
  name: 'Alex Johnson',
  email: 'alex@example.com',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDlBy-yCwRN_SXsMlaM4lZx1TGx3g1_o33z6eONLlrWYTDYJyZqGv7sAO7Ydu2yUwahMv9psKT3tkUwi10kwrtdZOrURcKgetzQxTTALFhqAGPdbcVl69LqluPxtMSt8tOlvS_2tRE7nrmSSW_kKk1sv49CIkbis5poNzgsw2iAS4xpTmmHi6WqZthbptv45LRJhdU37KbYw2_94_idgzvFyqmSW3IXnizwXC-A7gBbt0HNFATojzkR',
  countriesVisited: 12,
  tripsPlanned: 3,
};

export const mockTrips = [
  {
    id: 1,
    name: 'Tokyo, Japan',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQvYuSZnqRoCQiLXziTFGKLrI6C0KROMgff7yBNYZW2J3UTBNO3hiNr8kA9Qty_JAT1zLrpiT089Kc03Slqo3e42_Jtwb09UpULIwsRk8eP1XPQ4klVgzmw7fQrpftg0qr6HqI4RS8oO4jj4nBESVEJyzryBSX7g1yIecXYPEYK98mz7ULd9G3-WcqUUcIA4i1NyODNeJBL0AmFUZ82j18Yf1bvOAqL_yVFkv1qPYLpiZZGRRja0A4',
    startDate: '2024-10-12',
    endDate: '2024-10-26',
    daysUntil: 14,
    progress: 80,
    status: 'upcoming',
    budget: 4500,
    stops: ['Tokyo', 'Kyoto', 'Osaka'],
    days: [
      {
        date: '2024-10-12',
        day: 1,
        city: 'Tokyo',
        activities: [
          { id: 1, name: 'Hotel Check-in', time: '14:00', icon: 'hotel', category: 'accommodation', cost: 0, notes: 'Park Hyatt Tokyo' },
          { id: 2, name: 'Shibuya Crossing', time: '17:00', icon: 'location_city', category: 'sightseeing', cost: 0, notes: 'Walk around Shibuya district' },
          { id: 3, name: 'Dinner at Ukai Tofuya', time: '19:30', icon: 'restaurant', category: 'food', cost: 120, notes: 'Traditional Japanese cuisine' },
        ],
      },
      {
        date: '2024-10-13',
        day: 2,
        city: 'Tokyo',
        activities: [
          { id: 4, name: 'Tsukiji Fish Market', time: '07:00', icon: 'storefront', category: 'food', cost: 30, notes: 'Fresh sushi breakfast' },
          { id: 5, name: 'Senso-ji Temple', time: '10:00', icon: 'account_balance', category: 'culture', cost: 0, notes: 'Asakusa district' },
          { id: 6, name: 'teamLab Borderless', time: '14:00', icon: 'auto_awesome', category: 'entertainment', cost: 35, notes: 'Digital art museum' },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Amalfi Coast, Italy',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDbsolaiAp4Twf3ki_flbmv1g3YmjuoYJd1jVvireJfQO4628jJv6KXZ9qNvq-K8Y3G2sHkVmUUzykU0WWQkvjSiRzDlBHlyGVD58R-QfWVU9-dk8cX2uWEWMOR195fcbgDCpmfT4tq9La27d-yw0Ln6pe1pAqnp-e3ggPqxDzu0ww0Eo0nk3H3P6La6YuKlU98B5yXSD88jQEAipTFsZ0oFvGdB6M1S_bumBg2bQKUoOFObsQnQSAW',
    startDate: '2025-05-05',
    endDate: '2025-05-15',
    daysUntil: 90,
    progress: 35,
    status: 'planning',
    budget: 3200,
    stops: ['Naples', 'Positano', 'Amalfi'],
    days: [],
  },
  {
    id: 3,
    name: 'Bali, Indonesia',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbvyzdwWjwWx72cKKz2KZuZL6EhydF9tvP8WmNlQIlajYbY8UVWfnKwElr7NJ6Y8awOTlV4HMd_CITNB1UVEnjp4np7zr33DoGVK0fp7YWj_0TDDjRs3RdPA5G_iTZ7zUYKHUwdfYI0sB8APid_Z7JH19yRi2JkRY2xtJrPigwhz1ljvOwmjs0J-dZq4UlBRv8Y3bSLsxJnneGcZpetdzbNRJ-HAzjOWExjMTdZe73KhD0I7Rn3wEW',
    startDate: '2025-07-01',
    endDate: '2025-07-14',
    daysUntil: 180,
    progress: 10,
    status: 'idea',
    budget: 2800,
    stops: ['Ubud', 'Seminyak', 'Nusa Dua'],
    days: [],
  },
];

export const mockDestinations = [
  {
    id: 1,
    name: 'Bali, Indonesia',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbvyzdwWjwWx72cKKz2KZuZL6EhydF9tvP8WmNlQIlajYbY8UVWfnKwElr7NJ6Y8awOTlV4HMd_CITNB1UVEnjp4np7zr33DoGVK0fp7YWj_0TDDjRs3RdPA5G_iTZ7zUYKHUwdfYI0sB8APid_Z7JH19yRi2JkRY2xtJrPigwhz1ljvOwmjs0J-dZq4UlBRv8Y3bSLsxJnneGcZpetdzbNRJ-HAzjOWExjMTdZe73KhD0I7Rn3wEW',
    country: 'Indonesia',
    region: 'Southeast Asia',
    bestTime: 'Jun–Sep',
    priceLevel: '$$',
    popularity: 95,
    category: 'Beach',
    badge: 'High Demand',
    badgeVariant: 'surface',
  },
  {
    id: 2,
    name: 'Swiss Alps',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrz1MMqlXb4Y7ypMjO2Zj-zJ7NvuftKFcperzr6NZ8nNTyBp6iMZjb68N_BijRFa1tMDYBfHHnh3vI0HF-JApxr0H1RK_PJkJoJYjxDzgLwAhkisd7fOBj0osgj5i2sHQrXjXJwszJTyjrOlk3uR23SvAFu-ZFXmndmCPwxDOMf4VRzAIcuDVh6h9SfMFzBIs4-PTwV6tYOfonb7HzpbXXHxYfR3N-_VoAiEhIbm7jFD58UPD-_dhl',
    country: 'Switzerland',
    region: 'Europe',
    bestTime: 'Dec–Mar',
    priceLevel: '$$$$',
    popularity: 88,
    category: 'Adventure',
    badge: null,
  },
  {
    id: 3,
    name: 'Marrakech, Morocco',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvpY6w3sF_k9PZ2FZYoxC1eCx4w63WvazmBLdLS3uOAeqGufurxRVaEue8vSqFucdKCHTmKg4C1M3FTb5CEY7EuhyTxFuF45e-PRwoqZ5Y0paiwUA-JhpaZAY4A5ISwuaKnuXRlFTw8UGlyCdrZToIYACJuX-8KdjiP8MF6MSdAiML8HqIEG_KSucGU8OrbZg6o-syBQSOZZlNmBbSzWKAOJTJxvPGyn3xokw7CmLSg3bU14otP5OD',
    country: 'Morocco',
    region: 'Africa',
    bestTime: 'Mar–May',
    priceLevel: '$',
    popularity: 82,
    category: 'Culture',
    badge: 'Trending',
    badgeVariant: 'secondary',
  },
  {
    id: 4,
    name: 'Kyoto, Japan',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQvYuSZnqRoCQiLXziTFGKLrI6C0KROMgff7yBNYZW2J3UTBNO3hiNr8kA9Qty_JAT1zLrpiT089Kc03Slqo3e42_Jtwb09UpULIwsRk8eP1XPQ4klVgzmw7fQrpftg0qr6HqI4RS8oO4jj4nBESVEJyzryBSX7g1yIecXYPEYK98mz7ULd9G3-WcqUUcIA4i1NyODNeJBL0AmFUZ82j18Yf1bvOAqL_yVFkv1qPYLpiZZGRRja0A4',
    country: 'Japan',
    region: 'Asia',
    bestTime: 'Mar–May',
    priceLevel: '$$$',
    popularity: 91,
    category: 'Culture',
    badge: null,
  },
  {
    id: 5,
    name: 'New York City, USA',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQvYuSZnqRoCQiLXziTFGKLrI6C0KROMgff7yBNYZW2J3UTBNO3hiNr8kA9Qty_JAT1zLrpiT089Kc03Slqo3e42_Jtwb09UpULIwsRk8eP1XPQ4klVgzmw7fQrpftg0qr6HqI4RS8oO4jj4nBESVEJyzryBSX7g1yIecXYPEYK98mz7ULd9G3-WcqUUcIA4i1NyODNeJBL0AmFUZ82j18Yf1bvOAqL_yVFkv1qPYLpiZZGRRja0A4',
    country: 'USA',
    region: 'North America',
    bestTime: 'Apr–Jun',
    priceLevel: '$$$',
    popularity: 96,
    category: 'City',
    badge: null,
  },
  {
    id: 6,
    name: 'Santorini, Greece',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWirBfU2VJJ6rV3xgTFkHCIGw0PC0U4-yj1kvgRy4H5M7VOGKQAz77ck2NZxHVKqvHt1_EvrhVEawVbN0KK5QWv0KEAsbefiSWtQjOTF_9VUPJbSC9jqih29bdcEZYa9hwkYYCW6ARDoLaKv9lkFaGgt0UCAsUFRvu8kCMj8mVhHV4Zh_hnAMPgcu66k1413B3EJyIBwQumKSVOuJl4YIS5tHR_dONjYmwraD4eeiGi9BBDq0dwsgX',
    country: 'Greece',
    region: 'Europe',
    bestTime: 'May–Oct',
    priceLevel: '$$$',
    popularity: 94,
    category: 'Beach',
    badge: null,
  },
];

export const mockActivities = [
  { id: 1, name: 'Louvre Museum Tour', description: 'Guided tour of the world\'s largest art museum.', duration: 180, cost: 25, category: 'sightseeing', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfVuh8ggjCbxpZAN_aUuI514v1Qs5BdaYop77uyNltgB6vSTqNyq1pniQ0uVUhcTTv87dyveLJ0LEVBl2FaX1Jj-dt10FaJS4xtBnGvHyEAoqoVRYrQbL3OOCWNzgNu2UVyE4_6zTgqo8DDCu6BOCkTzSD4jOf8rqoewiLmynZIgtwG3xwsSl4I5Ki7HdbnzVYnAIMYoWCBxtU0NzvTaFS2999dfFU3te17Z3AyjiBabO2RG0sI437' },
  { id: 2, name: 'Seine Dinner Cruise', description: 'Romantic evening cruise with fine dining.', duration: 120, cost: 95, category: 'food', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbvyzdwWjwWx72cKKz2KZuZL6EhydF9tvP8WmNlQIlajYbY8UVWfnKwElr7NJ6Y8awOTlV4HMd_CITNB1UVEnjp4np7zr33DoGVK0fp7YWj_0TDDjRs3RdPA5G_iTZ7zUYKHUwdfYI0sB8APid_Z7JH19yRi2JkRY2xtJrPigwhz1ljvOwmjs0J-dZq4UlBRv8Y3bSLsxJnneGcZpetdzbNRJ-HAzjOWExjMTdZe73KhD0I7Rn3wEW' },
  { id: 3, name: 'Eiffel Tower Visit', description: 'Skip-the-line ticket to the iconic iron tower.', duration: 90, cost: 30, category: 'sightseeing', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrz1MMqlXb4Y7ypMjO2Zj-zJ7NvuftKFcperzr6NZ8nNTyBp6iMZjb68N_BijRFa1tMDYBfHHnh3vI0HF-JApxr0H1RK_PJkJoJYjxDzgLwAhkisd7fOBj0osgj5i2sHQrXjXJwszJTyjrOlk3uR23SvAFu-ZFXmndmCPwxDOMf4VRzAIcuDVh6h9SfMFzBIs4-PTwV6tYOfonb7HzpbXXHxYfR3N-_VoAiEhIbm7jFD58UPD-_dhl' },
  { id: 4, name: 'Rock Climbing Session', description: 'Guided outdoor climbing for all skill levels.', duration: 240, cost: 65, category: 'adventure', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvpY6w3sF_k9PZ2FZYoxC1eCx4w63WvazmBLdLS3uOAeqGufurxRVaEue8vSqFucdKCHTmKg4C1M3FTb5CEY7EuhyTxFuF45e-PRwoqZ5Y0paiwUA-JhpaZAY4A5ISwuaKnuXRlFTw8UGlyCdrZToIYACJuX-8KdjiP8MF6MSdAiML8HqIEG_KSucGU8OrbZg6o-syBQSOZZlNmBbSzWKAOJTJxvPGyn3xokw7CmLSg3bU14otP5OD' },
  { id: 5, name: 'Local Cooking Class', description: 'Learn to cook authentic local dishes.', duration: 180, cost: 55, category: 'food', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBWirBfU2VJJ6rV3xgTFkHCIGw0PC0U4-yj1kvgRy4H5M7VOGKQAz77ck2NZxHVKqvHt1_EvrhVEawVbN0KK5QWv0KEAsbefiSWtQjOTF_9VUPJbSC9jqih29bdcEZYa9hwkYYCW6ARDoLaKv9lkFaGgt0UCAsUFRvu8kCMj8mVhHV4Zh_hnAMPgcu66k1413B3EJyIBwQumKSVOuJl4YIS5tHR_dONjYmwraD4eeiGi9BBDq0dwsgX' },
  { id: 6, name: 'City Walking Tour', description: '3-hour guided exploration of the historic city center.', duration: 180, cost: 15, category: 'culture', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAbvyzdwWjwWx72cKKz2KZuZL6EhydF9tvP8WmNlQIlajYbY8UVWfnKwElr7NJ6Y8awOTlV4HMd_CITNB1UVEnjp4np7zr33DoGVK0fp7YWj_0TDDjRs3RdPA5G_iTZ7zUYKHUwdfYI0sB8APid_Z7JH19yRi2JkRY2xtJrPigwhz1ljvOwmjs0J-dZq4UlBRv8Y3bSLsxJnneGcZpetdzbNRJ-HAzjOWExjMTdZe73KhD0I7Rn3wEW' },
  { id: 7, name: 'Sunset Yoga Class', description: 'Beachside yoga session at golden hour.', duration: 75, cost: 20, category: 'relax', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBrz1MMqlXb4Y7ypMjO2Zj-zJ7NvuftKFcperzr6NZ8nNTyBp6iMZjb68N_BijRFa1tMDYBfHHnh3vI0HF-JApxr0H1RK_PJkJoJYjxDzgLwAhkisd7fOBj0osgj5i2sHQrXjXJwszJTyjrOlk3uR23SvAFu-ZFXmndmCPwxDOMf4VRzAIcuDVh6h9SfMFzBIs4-PTwV6tYOfonb7HzpbXXHxYfR3N-_VoAiEhIbm7jFD58UPD-_dhl' },
  { id: 8, name: 'Night Jazz Concert', description: 'Live jazz performance at a historic venue.', duration: 120, cost: 40, category: 'entertainment', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvpY6w3sF_k9PZ2FZYoxC1eCx4w63WvazmBLdLS3uOAeqGufurxRVaEue8vSqFucdKCHTmKg4C1M3FTb5CEY7EuhyTxFuF45e-PRwoqZ5Y0paiwUA-JhpaZAY4A5ISwuaKnuXRlFTw8UGlyCdrZToIYACJuX-8KdjiP8MF6MSdAiML8HqIEG_KSucGU8OrbZg6o-syBQSOZZlNmBbSzWKAOJTJxvPGyn3xokw7CmLSg3bU14otP5OD' },
];

export const mockBudget = {
  total: 4500,
  spent: 2100,
  categories: [
    { name: 'Accommodation', amount: 900, color: '#0057d9', icon: 'hotel' },
    { name: 'Transport', amount: 650, color: '#fe7944', icon: 'flight' },
    { name: 'Activities', amount: 350, color: '#624315', icon: 'attractions' },
    { name: 'Meals', amount: 200, color: '#2ecc71', icon: 'restaurant' },
    { name: 'Shopping', amount: 150, color: '#9b59b6', icon: 'shopping_bag' },
    { name: 'Other', amount: -150, color: '#95a5a6', icon: 'more_horiz' },
  ],
};
