// Mock data for Safar-sutra Travel Planner

export const mockUser = {
  id: 1,
  name: 'Alex Johnson',
  email: 'alex.traveler@gmail.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  countriesVisited: 14,
  tripsPlanned: 4,
  bio: 'Passionate about cultural heritage, ancient temple architecture, and scenic trail journeys.',
  savedDestinations: [1, 2, 4],
};

export const mockTrips = [
  {
    id: 1,
    name: 'Sacred Ayodhya & Varanasi Heritage',
    coverImage: '/assets/Ayodhya-Ram-Mandir-Images15.jpg',
    startDate: '2025-10-10',
    endDate: '2025-10-18',
    daysUntil: 12,
    progress: 85,
    status: 'upcoming',
    budget: 3500,
    spent: 2450,
    stops: ['Ayodhya', 'Varanasi', 'Prayagraj'],
    description: 'A deeply spiritual and cultural expedition exploring the grand temples and ancient ghats.',
    days: [
      {
        day: 1,
        date: '2025-10-10',
        city: 'Ayodhya',
        activities: [
          { id: 101, name: 'Darshan at Shri Ram Janmabhoomi Mandir', time: '08:00', icon: 'temple_hindu', category: 'Spiritual', cost: 0, notes: 'Morning Aarti & grand temple complex walk' },
          { id: 102, name: 'Sarayu River Aarti & Ghat Walk', time: '18:00', icon: 'water', category: 'Culture', cost: 20, notes: 'Sunset boating and devotional evening Aarti' },
          { id: 103, name: 'Traditional Awadhi Satvik Dinner', time: '20:30', icon: 'restaurant', category: 'Food & Dining', cost: 35, notes: 'Authentic local cuisine near Ram Ki Paidi' },
        ],
      },
      {
        day: 2,
        date: '2025-10-11',
        city: 'Ayodhya',
        activities: [
          { id: 104, name: 'Hanuman Garhi & Kanak Bhawan', time: '09:00', icon: 'account_balance', category: 'Heritage', cost: 10, notes: 'Historic hilltop fort-temple' },
          { id: 105, name: 'Heritage Museum & Cultural Center', time: '14:30', icon: 'museum', category: 'Sightseeing', cost: 15, notes: 'Ramayana art and historical artifacts' },
        ],
      },
      {
        day: 3,
        date: '2025-10-12',
        city: 'Varanasi',
        activities: [
          { id: 106, name: 'Kashi Vishwanath Temple Corridor', time: '07:30', icon: 'temple_hindu', category: 'Spiritual', cost: 0, notes: 'Darshan through the sacred river corridor' },
          { id: 107, name: 'Grand Ganga Aarti at Dashashwamedh', time: '18:30', icon: 'flare', category: 'Spiritual', cost: 25, notes: 'Mesmerizing synchronized evening lamps' },
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Royal Rajasthan: Forts & Palaces',
    coverImage: '/assets/Jaipur.jpeg',
    startDate: '2025-11-15',
    endDate: '2025-11-24',
    daysUntil: 45,
    progress: 50,
    status: 'planning',
    budget: 4200,
    spent: 1800,
    stops: ['Jaipur', 'Udaipur', 'Jodhpur'],
    description: 'Experiencing the royalty, vibrant bazaars, and architectural marvels of the Desert Kingdom.',
    days: [
      {
        day: 1,
        date: '2025-11-15',
        city: 'Jaipur',
        activities: [
          { id: 201, name: 'Hawa Mahal & City Palace Tour', time: '09:30', icon: 'castle', category: 'Heritage', cost: 40, notes: 'Explore royal courtyards and astronomical observatory' },
          { id: 202, name: 'Sunset at Nahargarh Fort', time: '17:00', icon: 'photo_camera', category: 'Sightseeing', cost: 20, notes: 'Panoramic pink city sunset view' },
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Assam & Brahmaputra Wilderness',
    coverImage: '/assets/Assam.jpeg',
    startDate: '2026-01-05',
    endDate: '2026-01-14',
    daysUntil: 95,
    progress: 20,
    status: 'idea',
    budget: 3100,
    spent: 600,
    stops: ['Guwahati', 'Kaziranga', 'Majuli'],
    description: 'Safari into the home of the one-horned rhino and rolling lush green tea estates.',
    days: [],
  },
  {
    id: 4,
    name: 'Tropical Serenity in Andaman',
    coverImage: '/assets/andaman-nicobar.jpg',
    startDate: '2026-03-01',
    endDate: '2026-03-09',
    daysUntil: 150,
    progress: 10,
    status: 'idea',
    budget: 2900,
    spent: 0,
    stops: ['Port Blair', 'Havelock', 'Neil Island'],
    description: 'Turquoise ocean waters, scuba diving, and relaxation on pristine white sandy beaches.',
    days: [],
  },
];

export const mockDestinations = [
  {
    id: 1,
    name: 'Ayodhya',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North India',
    image: '/assets/Ayodhya-Ram-Mandir-Images15.jpg',
    bestTime: 'Oct–Mar',
    priceLevel: '$$',
    popularity: 98,
    costIndex: 'Affordable',
    category: 'Spiritual',
    badge: 'Trending Sacred',
    lat: 26.7922,
    lng: 82.1998,
    description: 'Ancient holy city on the banks of Sarayu, home of Shri Ram Janmabhoomi.',
  },
  {
    id: 2,
    name: 'Jaipur',
    state: 'Rajasthan',
    country: 'India',
    region: 'North India',
    image: '/assets/Jaipur.jpeg',
    bestTime: 'Nov–Feb',
    priceLevel: '$$$',
    popularity: 95,
    costIndex: 'Moderate',
    category: 'Heritage',
    badge: 'Royal Wonder',
    lat: 26.9124,
    lng: 75.7873,
    description: 'The historic Pink City with grand forts, palaces, and vibrant Rajasthani culture.',
  },
  {
    id: 3,
    name: 'Kaziranga & Assam',
    state: 'Assam',
    country: 'India',
    region: 'North East India',
    image: '/assets/Assam.jpeg',
    bestTime: 'Nov–Apr',
    priceLevel: '$$',
    popularity: 91,
    costIndex: 'Affordable',
    category: 'Nature',
    badge: 'Eco Sanctuary',
    lat: 26.5775,
    lng: 93.1711,
    description: 'UNESCO World Heritage wildlife haven with sprawling emerald tea plantations.',
  },
  {
    id: 4,
    name: 'Havelock & Andaman',
    state: 'Andaman & Nicobar',
    country: 'India',
    region: 'Islands',
    image: '/assets/andaman-nicobar.jpg',
    bestTime: 'Oct–May',
    priceLevel: '$$$$',
    popularity: 94,
    costIndex: 'Premium',
    category: 'Beach & Island',
    badge: 'Tropical Bliss',
    lat: 11.9761,
    lng: 92.9876,
    description: 'Pristine coral reefs, azure lagoons, and tranquil tropical island beaches.',
  },
  {
    id: 5,
    name: 'Varanasi',
    state: 'Uttar Pradesh',
    country: 'India',
    region: 'North India',
    image: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&auto=format&fit=crop&q=80',
    bestTime: 'Oct–Mar',
    priceLevel: '$',
    popularity: 97,
    costIndex: 'Budget Friendly',
    category: 'Spiritual',
    badge: 'Ancient City',
    lat: 25.3176,
    lng: 82.9739,
    description: 'The eternal spiritual capital of India along the sacred river Ganges.',
  },
  {
    id: 6,
    name: 'Kyoto',
    state: 'Kansai',
    country: 'Japan',
    region: 'International',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=600&auto=format&fit=crop&q=80',
    bestTime: 'Mar–May',
    priceLevel: '$$$$',
    popularity: 92,
    costIndex: 'Premium',
    category: 'Heritage',
    badge: 'Ancient Imperial',
    lat: 35.0116,
    lng: 135.7681,
    description: 'Classical Buddhist temples, magnificent gardens, imperial palaces, and traditional wooden houses.',
  },
];

export const mockActivities = [
  { id: 1, name: 'Ram Janmabhoomi Darshan & Parikrama', city: 'Ayodhya', duration: 180, cost: 0, category: 'Spiritual', image: '/assets/Ayodhya-Ram-Mandir-Images15.jpg', description: 'Sacred pilgrimage to the grand temple complex and sacred sanctum.' },
  { id: 2, name: 'Sarayu Sunset River Cruise & Aarti', city: 'Ayodhya', duration: 90, cost: 25, category: 'Culture', image: '/assets/Ayodhya-Ram-Mandir-Images15.jpg', description: 'Peaceful boat ride during the grand evening Aarti lamps.' },
  { id: 3, name: 'Amber Fort Elephant Safari & Palace', city: 'Jaipur', duration: 240, cost: 45, category: 'Heritage', image: '/assets/Jaipur.jpeg', description: 'Explore mirror palaces, royal halls, and ramparts overlooking Maota lake.' },
  { id: 4, name: 'Kaziranga Elephant & Jeep Wildlife Safari', city: 'Kaziranga', duration: 210, cost: 60, category: 'Nature', image: '/assets/Assam.jpeg', description: 'Spot one-horned rhinos, wild elephants, and exotic birds at sunrise.' },
  { id: 5, name: 'Radhanagar Beach Scuba & Coral Snorkeling', city: 'Havelock', duration: 150, cost: 75, category: 'Adventure', image: '/assets/andaman-nicobar.jpg', description: 'Dive among colorful marine life in Asia’s best rated white sand beach.' },
  { id: 6, name: 'Authentic Royal Thali Culinary Workshop', city: 'Jaipur', duration: 120, cost: 35, category: 'Food & Dining', image: '/assets/Jaipur.jpeg', description: 'Learn the secrets of traditional Dal Baati Churma and Rajasthani sweets.' },
];

export const mockBudgetOverview = {
  totalAllocated: 13700,
  totalSpent: 4850,
  avgCostPerDay: 195,
  categories: [
    { name: 'Accommodation & Stays', amount: 2100, budget: 5000, color: '#4A2E18', icon: 'hotel' },
    { name: 'Transport & Flights', amount: 1450, budget: 4000, color: '#C88A4B', icon: 'flight' },
    { name: 'Activities & Guided Tours', amount: 750, budget: 2500, color: '#8D582A', icon: 'temple_hindu' },
    { name: 'Food & Dining', amount: 450, budget: 1500, color: '#A06D3B', icon: 'restaurant' },
    { name: 'Shopping & Souvenirs', amount: 100, budget: 700, color: '#D4A373', icon: 'shopping_bag' },
  ],
};

export const mockPlatformAnalytics = {
  totalUsers: 18450,
  tripsCreated: 4210,
  activeTravelers: 3120,
  destinationsCovered: 148,
  topDestinations: [
    { city: 'Ayodhya', trips: 1420, trend: '+45%' },
    { city: 'Jaipur', trips: 980, trend: '+18%' },
    { city: 'Varanasi', trips: 890, trend: '+32%' },
    { city: 'Andaman', trips: 640, trend: '+12%' },
    { city: 'Assam', trips: 480, trend: '+22%' },
  ],
  popularActivityTypes: [
    { type: 'Spiritual & Pilgrimage', pct: 42 },
    { type: 'Heritage & Forts', pct: 28 },
    { type: 'Nature & Wildlife', pct: 16 },
    { type: 'Adventure & Beaches', pct: 14 },
  ],
};
